import {
  notifySaleAdded,
  notifySaleUpdated,
  notifySaleDeleted,
  notifyPatientAdded,
  notifyPatientUpdated,
  notifyPatientDeleted,
  notifyStaffAdded,
  notifyStaffUpdated,
  notifyStaffDeleted,
  notifyAdvanceRecorded,
  notifyMonthClosed,
  notifyMonthlyReportCreated,
  notifyExpenseAdded,
  notifyExpenseUpdated,
  notifyExpenseDeleted,
  notifyInstallmentAdded,
  notifyInstallmentPayment,
  notifyInstallmentDeleted,
  notifySettingsUpdated,
  notifyActionError,
} from '@/lib/notify'

/** هوک بۆ نۆتیفیکەیشن — toast + پانێڵی زەنگ */
export function useNotificationHelper() {
  return {
    notifySale: notifySaleAdded,
    notifySaleUpdated,
    notifySaleDeleted,
    notifyPatient: notifyPatientAdded,
    notifyPatientUpdated,
    notifyPatientDeleted,
    notifyStaff: notifyStaffAdded,
    notifyStaffUpdated,
    notifyStaffDeleted,
    notifyAdvance: notifyAdvanceRecorded,
    notifyMonthClosed,
    notifyMonthlyReport: notifyMonthlyReportCreated,
    notifyExpenseAdded,
    notifyExpenseUpdated,
    notifyExpenseDeleted,
    notifyInstallmentAdded,
    notifyInstallmentPayment,
    notifyInstallmentDeleted,
    notifySettingsUpdated,
    notifySuccess: notifySettingsUpdated,
    notifyError: notifyActionError,
    notifyInfo: (title: string, message: string) =>
      notifySettingsUpdated(title, message),
  }
}
